### ISSUE TITLE
Reload data enters the delegate methods only one time

### ISSUE THREAD

**Issue by antonyjoemathew** [Daij-Djan/DDCalendarView#4]
Hi,
I am facing an issue,In my application I wan to reload the datas dynamically at different times.I am calling reloadData() but it is not entering in the delegate methods. I am using swift component
Thanks

**Comment by Daij-Djan** [comment]
I updated the calendar component a lot today and would urge you to retry this.
if it doesn't work plz try to clearly state what you are doing that doesn't work / what you try & expect.

I can confirm that the reloading works. The swift example even loads everything asynchronously

**Comment by YogeshBharate** [comment]
Hi @Daij-Djan,

I am facing same issue. :(

Description:
        I was fetching data from server for today's appointments, once I got the data I reloaded the calendarView. I was also checked this reloadData functionality with new version 2.0, but facing same issue.
 This is [my code](http://pastebin.com/ZEECi98e). If I am wrong somewhere please correct me. Thanks in advance !!!!

**Comment by Daij-Djan** [comment]
@YogeshBharate I see you call reloadData in loadEvents inside the completionBlock of getTodaysScheduleAppointments. Is it on the main thread? try to add: `assert(NSThread.isMainThread())` before calling reloadData

**Comment by Daij-Djan** [comment]
if that is the issue: `dispatch_async(dispatch_get_main_queue()) { self.calenderView.reloadData() }`

if not, please provide me a small runnabe example... if possible

**Comment by YogeshBharate** [comment]
@Daij-Djan I tried what you said in the above comment, but still the issue exists. I have created a [small runnable demo](https://github.com/YogeshBharate/CalendarView), where when I got data, then I reloaded calendar view, but it has not loaded. Please Check the demo.

**Comment by Daij-Djan** [comment]
the component works fine but your code has serveral isssues:

1. the main issue is, that swift arrays are passed-by-value and not by reference. you attempt to fill ddEvents after you store in dict.... so the dict remains empty at all times

2. the data you provide is wrong. e.g. the sample gets 6 events for the 10th of august BUT you save that for the 9th .. so the events are shown WAY down

---

the fix for 1. is .... save the ddevents in the dict 
the fix for 2. is .... fix the data. ;)

->for 1 the bug could be the misuse of focussed on day. that method isnt called for reloadData.

so I removed your func calendarViewfocussedOnDay and changed eventsForDay to load data if needed:

	func calendarView(view: DDCalendarView, eventsForDay date: NSDate) -> [AnyObject]? {
	let days = date.daysFromDate(NSDate())
	if dict[days] == nil {
		self.loadCachedEvents(days) { (events) -> Void in
			self.showData()
			print("DAY: \(days)")
		}
	}
	return dict[days]
	}

I also fixed fillEvents to reset the dict

LAST I fixed the json data so the 9th is mapped to today..  just so I didnt always have to swipe to tommorrow :D

**Comment by YogeshBharate** [comment]
Great !!! Can you update your code to [CalendarView repo](https://github.com/YogeshBharate/CalendarView.git) ? Thanks in advance !!! This is the [invitation link](https://github.com/YogeshBharate/CalendarView/invitations) to update repo.
